# Copyright 2022 VMware, Inc.
# SPDX-License-Identifier: MIT

from .base import *

VTAAS_SERVER='https://localhost'
VTAAS_SERVER_BE='http://localhost:8000'
VTAAS_SSL_SERVER=VTAAS_SERVER
REPORT_ISSUE_SERVER=VTAAS_SERVER
ACCESSIBILITY_PAGECACHE_SERVER=VTAAS_SERVER+':9004'